import { ERandomOption, IElementDefinition } from '../typings';

const animalAerial: IElementDefinition = {
  type: 'animal_aerial',
  text: 'animal_aerial',
  options: [{
    type: 'animal_aerial',
    text: 'animal_aerial_1',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_2',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_3',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_4',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_5',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_6',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_7',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_8',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_9',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_10',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_11',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_12',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_13',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_14',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_15',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_16',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_17',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_18',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_19',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_20',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_21',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_22',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_23',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_24',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_25',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_26',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_27',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_28',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_29',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_30',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_31',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_32',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_33',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_34',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_35',
  }, {
    type: 'animal_aerial',
    text: 'animal_aerial_36',
  }],
};

const animalTerrestrial: IElementDefinition = {
  type: 'animal_terrestrial',
  text: 'animal_terrestrial',
  options: [{
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_1',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_2',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_3',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_4',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_5',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_6',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_7',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_8',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_9',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_10',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_11',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_12',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_13',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_14',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_15',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_16',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_17',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_18',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_19',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_20',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_21',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_22',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_23',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_24',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_25',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_26',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_27',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_28',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_29',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_30',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_31',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_32',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_33',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_34',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_35',
  }, {
    type: 'animal_terrestrial',
    text: 'animal_terrestrial_36',
  }],
};

const animalAquatic: IElementDefinition = {
  type: 'animal_aquatic',
  text: 'animal_aquatic',
  options: [{
    type: 'animal_aquatic',
    text: 'animal_aquatic_1',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_2',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_3',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_4',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_5',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_6',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_7',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_8',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_9',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_10',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_11',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_12',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_13',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_14',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_15',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_16',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_17',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_18',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_19',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_20',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_21',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_22',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_23',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_24',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_25',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_26',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_27',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_28',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_29',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_30',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_31',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_32',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_33',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_34',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_35',
  }, {
    type: 'animal_aquatic',
    text: 'animal_aquatic_36',
  }],
};

export {
  animalTerrestrial,
  animalAerial,
  animalAquatic,
};
