import { ERandomOption, IElementDefinition } from '../typings';

const cityBuilding: IElementDefinition = {
  type: 'city_building',
  text: 'city_building',
  options: [{
    type: 'city_building',
    text: 'city_lowerclass_building',
    related: {
      city_lowerclass_building: { search: [{ type: 'city_lowerclass_building' }] },
    },
  }, {
    type: 'city_building',
    text: 'city_upperclass_building',
    related: {
      city_upperclass_building: { search: [{ type: 'city_upperclass_building' }] },
    },
  }],
};

const cityTheme: IElementDefinition = {
  type: 'city_theme',
  text: 'city_theme',
  options: [{
    type: 'city_theme',
    text: 'city_theme_1',
    related: { animal: { search: [{ type: 'animal' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_2',
  }, {
    type: 'city_theme',
    text: 'city_theme_3',
  }, {
    type: 'city_theme',
    text: 'city_theme_4',
  }, {
    type: 'city_theme',
    text: 'city_theme_5',
  }, {
    type: 'city_theme',
    text: 'city_theme_6',
  }, {
    type: 'city_theme',
    text: 'city_theme_7',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_8',
    related: { city_event: { search: [{ type: 'city_event' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_9',
  }, {
    type: 'city_theme',
    text: 'city_theme_10',
  }, {
    type: 'city_theme',
    text: 'city_theme_11',
    related: { city_district_theme: { search: [{ type: 'city_district_theme' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_12',
    related: { divinity_domain: { search: [{ type: 'divinity_domain' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_13',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_14',
  }, {
    type: 'city_theme',
    text: 'city_theme_15',
  }, {
    type: 'city_theme',
    text: 'city_theme_16',
  }, {
    type: 'city_theme',
    text: 'city_theme_17',
    related: { city_lowerclass_building: { search: [{ type: 'city_lowerclass_building' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_18',
  }, {
    type: 'city_theme',
    text: 'city_theme_19',
  }, {
    type: 'city_theme',
    text: 'city_theme_20',
    related: { npc: { search: [{ type: 'npc', random: ERandomOption.all }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_21',
  }, {
    type: 'city_theme',
    text: 'city_theme_22',
    related: { physical_element: { search: [{ type: 'physical_element' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_23',
  }, {
    type: 'city_theme',
    text: 'city_theme_24',
  }, {
    type: 'city_theme',
    text: 'city_theme_25',
  }, {
    type: 'city_theme',
    text: 'city_theme_26',
  }, {
    type: 'city_theme',
    text: 'city_theme_27',
  }, {
    type: 'city_theme',
    text: 'city_theme_28',
  }, {
    type: 'city_theme',
    text: 'city_theme_29',
  }, {
    type: 'city_theme',
    text: 'city_theme_30',
  }, {
    type: 'city_theme',
    text: 'city_theme_31',
  }, {
    type: 'city_theme',
    text: 'city_theme_32',
  }, {
    type: 'city_theme',
    text: 'city_theme_33',
  }, {
    type: 'city_theme',
    text: 'city_theme_34',
    related: { city_uperclass_building: { search: [{ type: 'city_uperclass_building' }] } },
  }, {
    type: 'city_theme',
    text: 'city_theme_35',
  }, {
    type: 'city_theme',
    text: 'city_theme_36',
  }],
};

const cityEvent: IElementDefinition = {
  type: 'city_event',
  text: 'city_event',
  options: [{
    type: 'city_event',
    text: 'city_event_1',
  }, {
    type: 'city_event',
    text: 'city_event_2',
  }, {
    type: 'city_event',
    text: 'city_event_3',
  }, {
    type: 'city_event',
    text: 'city_event_4',
  }, {
    type: 'city_event',
    text: 'city_event_5',
  }, {
    type: 'city_event',
    text: 'city_event_6',
  }, {
    type: 'city_event',
    text: 'city_event_7',
  }, {
    type: 'city_event',
    text: 'city_event_8',
  }, {
    type: 'city_event',
    text: 'city_event_9',
  }, {
    type: 'city_event',
    text: 'city_event_10',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'city_event',
    text: 'city_event_11',
  }, {
    type: 'city_event',
    text: 'city_event_12',
  }, {
    type: 'city_event',
    text: 'city_event_13',
  }, {
    type: 'city_event',
    text: 'city_event_14',
  }, {
    type: 'city_event',
    text: 'city_event_15',
  }, {
    type: 'city_event',
    text: 'city_event_16',
  }, {
    type: 'city_event',
    text: 'city_event_17',
  }, {
    type: 'city_event',
    text: 'city_event_18',
  }, {
    type: 'city_event',
    text: 'city_event_19',
  }, {
    type: 'city_event',
    text: 'city_event_20',
  }, {
    type: 'city_event',
    text: 'city_event_21',
  }, {
    type: 'city_event',
    text: 'city_event_22',
  }, {
    type: 'city_event',
    text: 'city_event_23',
  }, {
    type: 'city_event',
    text: 'city_event_24',
  }, {
    type: 'city_event',
    text: 'city_event_25',
  }, {
    type: 'city_event',
    text: 'city_event_26',
  }, {
    type: 'city_event',
    text: 'city_event_27',
  }, {
    type: 'city_event',
    text: 'city_event_28',
  }, {
    type: 'city_event',
    text: 'city_event_29',
  }, {
    type: 'city_event',
    text: 'city_event_30',
  }, {
    type: 'city_event',
    text: 'city_event_31',
  }, {
    type: 'city_event',
    text: 'city_event_32',
  }, {
    type: 'city_event',
    text: 'city_event_33',
  }, {
    type: 'city_event',
    text: 'city_event_34',
  }, {
    type: 'city_event',
    text: 'city_event_35',
  }, {
    type: 'city_event',
    text: 'city_event_36',
  }],
};

const cityDistrictTheme: IElementDefinition = {
  type: 'city_district_theme',
  text: 'city_district_theme',
  options: [{
    type: 'city_district_theme',
    text: 'city_district_theme_1',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_2',
    related: { npc_civilized: { search: [{ type: 'npc_civilized', random: ERandomOption.all }] } },
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_3',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_4',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_5',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_6',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_7',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_8',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_9',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_10',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_11',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_12',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_13',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_14',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_15',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_16',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_17',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_18',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_19',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_20',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_21',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_22',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_23',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_24',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_25',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_26',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_27',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_28',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_29',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_30',
    related: { npc_underworld: { search: [{ type: 'npc_underworld', random: ERandomOption.all }] } },
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_31',
    related: { city_upperclass_building: { search: [{ type: 'city_upperclass_building' }] } },
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_32',
    related: { city_lowerclass_building: { search: [{ type: 'city_lowerclass_building' }] } },
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_33',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_34',
    related: { npc_wilderness: { search: [{ type: 'npc_wilderness', random: ERandomOption.all }] } },
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_35',
  }, {
    type: 'city_district_theme',
    text: 'city_district_theme_36',
  }],
};

const cityUpperclassBuilding: IElementDefinition = {
  type: 'city_upperclass_building',
  text: 'city_upperclass_building',
  options: [{
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_1',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_2',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_3',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_4',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_5',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_6',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_7',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_8',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_9',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_10',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_11',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_12',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_13',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_14',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_15',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_16',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_17',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_18',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_19',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_20',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_21',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_22',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_23',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_24',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_25',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_26',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_27',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_28',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_29',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_30',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_31',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_32',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_33',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_34',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_35',
  }, {
    type: 'city_upperclass_building',
    text: 'city_upperclass_building_36',
  }],
};

const cityLowerclassBuilding: IElementDefinition = {
  type: 'city_lowerclass_building',
  text: 'city_lowerclass_building',
  options: [{
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_1',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_2',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_3',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_4',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_5',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_6',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_7',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_8',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_9',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_10',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_11',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_12',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_13',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_14',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_15',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_16',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_17',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_18',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_19',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_20',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_21',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_22',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_23',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_24',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_25',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_26',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_27',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_28',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_29',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_30',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_31',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_32',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_33',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_34',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_35',
  }, {
    type: 'city_lowerclass_building',
    text: 'city_lowerclass_building_36',
  }],
};

const cityActivity: IElementDefinition = {
  type: 'city_activity',
  text: 'city_activity',
  options: [{
    type: 'city_activity',
    text: 'city_activity_1',
  }, {
    type: 'city_activity',
    text: 'city_activity_2',
  }, {
    type: 'city_activity',
    text: 'city_activity_3',
  }, {
    type: 'city_activity',
    text: 'city_activity_4',
  }, {
    type: 'city_activity',
    text: 'city_activity_5',
  }, {
    type: 'city_activity',
    text: 'city_activity_6',
  }, {
    type: 'city_activity',
    text: 'city_activity_7',
  }, {
    type: 'city_activity',
    text: 'city_activity_8',
  }, {
    type: 'city_activity',
    text: 'city_activity_9',
  }, {
    type: 'city_activity',
    text: 'city_activity_10',
  }, {
    type: 'city_activity',
    text: 'city_activity_11',
  }, {
    type: 'city_activity',
    text: 'city_activity_12',
  }, {
    type: 'city_activity',
    text: 'city_activity_13',
  }, {
    type: 'city_activity',
    text: 'city_activity_14',
  }, {
    type: 'city_activity',
    text: 'city_activity_15',
  }, {
    type: 'city_activity',
    text: 'city_activity_16',
  }, {
    type: 'city_activity',
    text: 'city_activity_17',
    related: { dungeon_activity: { search: [{ type: 'dungeon_activity' }] } },
  }, {
    type: 'city_activity',
    text: 'city_activity_18',
  }, {
    type: 'city_activity',
    text: 'city_activity_19',
  }, {
    type: 'city_activity',
    text: 'city_activity_20',
    related: { mission: { search: [{ type: 'mission' }] } },
  }, {
    type: 'city_activity',
    text: 'city_activity_21',
  }, {
    type: 'city_activity',
    text: 'city_activity_22',
  }, {
    type: 'city_activity',
    text: 'city_activity_23',
  }, {
    type: 'city_activity',
    text: 'city_activity_24',
  }, {
    type: 'city_activity',
    text: 'city_activity_25',
  }, {
    type: 'city_activity',
    text: 'city_activity_26',
  }, {
    type: 'city_activity',
    text: 'city_activity_27',
  }, {
    type: 'city_activity',
    text: 'city_activity_28',
  }, {
    type: 'city_activity',
    text: 'city_activity_29',
  }, {
    type: 'city_activity',
    text: 'city_activity_30',
  }, {
    type: 'city_activity',
    text: 'city_activity_31',
  }, {
    type: 'city_activity',
    text: 'city_activity_32',
  }, {
    type: 'city_activity',
    text: 'city_activity_33',
  }, {
    type: 'city_activity',
    text: 'city_activity_34',
  }, {
    type: 'city_activity',
    text: 'city_activity_35',
  }, {
    type: 'city_activity',
    text: 'city_activity_36',
    related: { wild_activity: { search: [{ type: 'wild_activity' }] } },
  }],
};

const cityBuildingRoom: IElementDefinition = {
  type: 'city_building_room',
  text: 'city_building_room',
  options: [{
    type: 'city_building_room',
    text: 'city_building_room_1',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_2',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_3',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_4',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_5',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_6',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_7',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_8',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_9',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_10',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_11',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_12',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_13',
    related: { dungeon_room: { search: [{ type: 'dungeon_room' }] } },
  }, {
    type: 'city_building_room',
    text: 'city_building_room_14',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_15',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_16',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_17',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_18',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_19',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_20',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_21',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_22',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_23',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_24',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_25',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_26',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_27',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_28',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_29',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_30',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_31',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_32',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_33',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_34',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_35',
  }, {
    type: 'city_building_room',
    text: 'city_building_room_36',
  }],
};

const cityTacticalStreetFeature: IElementDefinition = {
  type: 'city_tactical_street_feature',
  text: 'city_tactical_street_feature',
  options: [{
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_1',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_2',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_3',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_4',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_5',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_6',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_7',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_8',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_9',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_10',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_11',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_12',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_13',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_14',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_15',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_16',
    related: { dungeon_activity: { search: [{ type: 'dungeon_activity' }] } },
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_17',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_18',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_19',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_20',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_21',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_22',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_23',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_24',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_25',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_26',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_27',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_28',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_29',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_30',
    related: { wild_activity: { search: [{ type: 'wild_activity' }] } },
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_31',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_32',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_33',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_34',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_35',
  }, {
    type: 'city_tactical_street_feature',
    text: 'city_tactical_street_feature_36',
  }],
};

const cityTacticalBuildingFeature: IElementDefinition = {
  type: 'city_tactical_building_feature',
  text: 'city_tactical_building_feature',
  options: [{
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_1',
    related: { animal: { search: [{ type: 'animal' }] } },
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_2',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_3',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_4',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_5',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_6',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_7',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_8',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_9',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_10',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_11',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_12',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_13',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_14',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_15',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_16',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_17',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_18',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_19',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_20',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_21',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_22',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_23',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_24',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_25',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_26',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_27',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_28',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_29',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_30',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_31',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_32',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_33',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_34',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_35',
  }, {
    type: 'city_tactical_building_feature',
    text: 'city_tactical_building_feature_36',
  }],
};

export {
  cityTheme,
  cityEvent,
  cityDistrictTheme,
  cityBuilding,
  cityUpperclassBuilding,
  cityLowerclassBuilding,
  cityActivity,
  cityBuildingRoom,
  cityTacticalStreetFeature,
  cityTacticalBuildingFeature,
};
