import { ERandomOption, IElementDefinition } from '../typings';

const faction: IElementDefinition = {
  type: 'faction',
  text: 'faction',
  options: [{
    type: 'faction',
    text: 'faction_1',
  }, {
    type: 'faction',
    text: 'faction_2',
  }, {
    type: 'faction',
    text: 'faction_3',
  }, {
    type: 'faction',
    text: 'faction_4',
  }, {
    type: 'faction',
    text: 'faction_5',
  }, {
    type: 'faction',
    text: 'faction_6',
  }, {
    type: 'faction',
    text: 'faction_7',
  }, {
    type: 'faction',
    text: 'faction_8',
  }, {
    type: 'faction',
    text: 'faction_9',
  }, {
    type: 'faction',
    text: 'faction_10',
  }, {
    type: 'faction',
    text: 'faction_11',
  }, {
    type: 'faction',
    text: 'faction_12',
  }, {
    type: 'faction',
    text: 'faction_13',
  }, {
    type: 'faction',
    text: 'faction_14',
  }, {
    type: 'faction',
    text: 'faction_15',
  }, {
    type: 'faction',
    text: 'faction_16',
  }, {
    type: 'faction',
    text: 'faction_17',
  }, {
    type: 'faction',
    text: 'faction_18',
  }, {
    type: 'faction',
    text: 'faction_19',
  }, {
    type: 'faction',
    text: 'faction_20',
  }, {
    type: 'faction',
    text: 'faction_21',
  }, {
    type: 'faction',
    text: 'faction_22',
  }, {
    type: 'faction',
    text: 'faction_23',
  }, {
    type: 'faction',
    text: 'faction_24',
  }, {
    type: 'faction',
    text: 'faction_25',
  }, {
    type: 'faction',
    text: 'faction_26',
  }, {
    type: 'faction',
    text: 'faction_27',
  }, {
    type: 'faction',
    text: 'faction_28',
  }, {
    type: 'faction',
    text: 'faction_29',
  }, {
    type: 'faction',
    text: 'faction_30',
  }, {
    type: 'faction',
    text: 'faction_31',
  }, {
    type: 'faction',
    text: 'faction_32',
  }, {
    type: 'faction',
    text: 'faction_33',
  }, {
    type: 'faction',
    text: 'faction_34',
  }, {
    type: 'faction',
    text: 'faction_35',
  }, {
    type: 'faction',
    text: 'faction_36',
  }],
};

export {
  faction,
};
