import { ERandomOption, IElementDefinition } from '../typings';

const dungeon: IElementDefinition = {
  type: 'dungeon',
  text: 'dungeon',
  related: {
    entrance: { search: [{ type: 'dungeon_entrance'}] },
    form: { search: [{ type: 'dungeon_form'}] },
    layout: { search: [{ type: 'dungeon_layout'}] },
    ruination: { search: [{ type: 'dungeon_ruination'}] },
    reward: { search: [{ type: 'dungeon_reward'}] },
    tirck: { search: [{ type: 'dungeon_trick'}] },
  },
};

const dungeonEntrance: IElementDefinition = {
  type: 'dungeon_entrance',
  text: 'dungeon_entrance',
  options: [{
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_1',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_2',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_3',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_4',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_5',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_6',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_7',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_8',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_9',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_10',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_11',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_12',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_13',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_14',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_15',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_16',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_17',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_18',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_19',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_20',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_21',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_22',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_23',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_24',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_25',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_26',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_27',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_28',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_29',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_30',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_31',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_32',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_33',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_34',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_35',
  }, {
    type: 'dungeon_entrance',
    text: 'dungeon_entrance_36',
  }],
};

const dungeonForm: IElementDefinition = {
  type: 'dungeon_form',
  text: 'dungeon_form',
  options: [{
    type: 'dungeon_form',
    text: 'dungeon_form_1',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_2',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_3',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_4',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_5',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_6',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_7',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_8',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_9',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_10',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_11',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_12',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_13',
    related: { city_building_room: { search: [{ type: 'city_building_room' }] } },
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_14',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_15',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_16',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_17',
    related: { city_lowerclass_building: { search: [{ type: 'city_lowerclass_building' }] } },
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_18',
    related: { dungeon_room: { search: [{ type: 'dungeon_room' }] } },
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_19',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_20',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_21',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_22',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_23',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_24',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_25',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_26',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_27',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_28',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_29',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_30',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_31',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_32',
    related: { city_upperclass_building: { search: [{ type: 'city_upperclass_building' }] } },
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_33',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_34',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_35',
  }, {
    type: 'dungeon_form',
    text: 'dungeon_form_36',
  }],
};

const dungeonLayout: IElementDefinition = {
  type: 'dungeon_layout',
  text: 'dungeon_layout',
  options: [{
    type: 'dungeon_layout',
    text: 'dungeon_layout_1',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_2',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_3',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_4',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_5',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_6',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_7',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_8',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_9',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_10',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_11',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_12',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_13',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_14',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_15',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_16',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_17',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_18',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_19',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_20',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_21',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_22',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_23',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_24',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_25',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_26',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_27',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_28',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_29',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_30',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_31',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_32',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_33',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_34',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_35',
  }, {
    type: 'dungeon_layout',
    text: 'dungeon_layout_36',
  }],
};

const dungeonRuination: IElementDefinition = {
  type: 'dungeon_ruination',
  text: 'dungeon_ruination',
  options: [{
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_1',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_2',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_3',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_4',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_5',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_6',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_7',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_8',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_9',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_10',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_11',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_12',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_13',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_14',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_15',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_16',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_17',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_18',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_19',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_20',
    related: { insanity: { search: [{ type: 'insanity' }] } },
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_21',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_22',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_23',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_24',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_25',
    related: { mutation: { search: [{ type: 'mutation' }] } },
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_26',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_27',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_28',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_29',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_30',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_31',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_32',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_33',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_34',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_35',
  }, {
    type: 'dungeon_ruination',
    text: 'dungeon_ruination_36',
  }],
};

const dungeonReward: IElementDefinition = {
  type: 'dungeon_reward',
  text: 'dungeon_reward',
  options: [{
    type: 'dungeon_reward',
    text: 'dungeon_reward_1',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_2',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_3',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_4',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_5',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_6',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_7',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_8',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_9',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_10',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_11',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_12',
    related: { item: { search: [{ type: 'item' }] } },
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_13',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_14',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_15',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_16',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_17',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_18',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_19',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_20',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_21',
    related: { monster: { search: [{ type: 'monster' }] } },
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_22',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_23',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_24',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_25',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_26',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_27',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_28',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_29',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_30',
    related: { treasure: { search: [{ type: 'treasure' }] } },
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_31',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_32',
    related: { valuable_material: { search: [{ type: 'valuable_material' }] } },
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_33',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_34',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_35',
  }, {
    type: 'dungeon_reward',
    text: 'dungeon_reward_36',
  }],
};

const dungeonTrick: IElementDefinition = {
  type: 'dungeon_trick',
  text: 'dungeon_trick',
  options: [{
    type: 'dungeon_trick',
    text: 'dungeon_trick_1',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_2',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_3',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_4',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_5',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_6',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_7',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_8',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_9',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_10',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_11',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_12',
    related: { ethereal_effect: { search: [{ type: 'ethereal_effect' }] } },
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_13',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_14',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_15',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_16',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_17',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_18',
    related: { mission: { search: [{ type: 'mission' }] } },
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_19',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_20',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_21',
    related: { physical_effect: { search: [{ type: 'physical_effect' }] } },
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_22',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_23',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_24',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_25',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_26',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_27',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_28',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_29',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_30',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_31',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_32',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_33',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_34',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_35',
  }, {
    type: 'dungeon_trick',
    text: 'dungeon_trick_36',
  }],
};

const dungeonRoom: IElementDefinition = {
  type: 'dungeon_room',
  text: 'dungeon_room',
  options: [{
    type: 'dungeon_room',
    text: 'dungeon_room_1',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_2',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_3',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_4',
    related: { city_building_room: { search: [{ type: 'city_building_room' }] } },
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_5',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_6',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_7',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_8',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_9',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_10',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_11',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_12',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_13',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_14',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_15',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_16',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_17',
    related: { city_lowerclass_building: { search: [{ type: 'city_lowerclass_building' }] } },
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_18',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_19',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_20',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_21',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_22',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_23',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_24',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_25',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_26',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_27',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_28',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_29',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_30',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_31',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_32',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_33',
    related: { city_upperclass_building: { search: [{ type: 'city_upperclass_building' }] } },
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_34',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_35',
  }, {
    type: 'dungeon_room',
    text: 'dungeon_room_36',
  }],
};

const dungeonActivity: IElementDefinition = {
  type: 'dungeon_activity',
  text: 'dungeon_activity',
  options: [{
    type: 'dungeon_activity',
    text: 'dungeon_activity_1',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_2',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_3',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_4',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_5',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_6',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_7',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_8',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_9',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_10',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_11',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_12',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_13',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_14',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_15',
    related: { monster_tactic: { search: [{ type: 'monster_tactic' }] } },
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_16',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_17',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_18',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_19',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_20',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_21',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_22',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_23',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_24',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_25',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_26',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_27',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_28',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_29',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_30',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_31',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_32',
    related: { wild_activity: { search: [{ type: 'wild_activity' }] } },
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_33',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_34',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_35',
  }, {
    type: 'dungeon_activity',
    text: 'dungeon_activity_36',
  }],
};

const dungeonRoomDetail: IElementDefinition = {
  type: 'dungeon_room_detail',
  text: 'dungeon_room_detail',
  options: [{
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_1',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_2',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_3',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_4',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_5',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_6',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_7',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_8',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_9',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_10',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_11',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_12',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_13',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_14',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_15',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_16',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_17',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_18',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_19',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_20',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_21',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_22',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_23',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_24',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_25',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_26',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_27',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_28',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_29',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_30',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_31',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_32',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_33',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_34',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_35',
  }, {
    type: 'dungeon_room_detail',
    text: 'dungeon_room_detail_36',
  }],
};

const dungeonHazard: IElementDefinition = {
  type: 'dungeon_hazard',
  text: 'dungeon_hazard',
  options: [{
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_1',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_2',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_3',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_4',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_5',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_6',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_7',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_8',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_9',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_10',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_11',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_12',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_13',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_14',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_15',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_16',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_17',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_18',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_19',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_20',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_21',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_22',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_23',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_24',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_25',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_26',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_27',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_28',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_29',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_30',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_31',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_32',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_33',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_34',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_35',
  }, {
    type: 'dungeon_hazard',
    text: 'dungeon_hazard_36',
  }],
};

export {
  dungeon,
  dungeonEntrance,
  dungeonForm,
  dungeonLayout,
  dungeonRuination,
  dungeonReward,
  dungeonTrick,
  dungeonRoom,
  dungeonRoomDetail,
  dungeonHazard,
  dungeonActivity,
};
