import { ERandomOption, IElementDefinition } from '../typings';

const faction: IElementDefinition = {
  type: 'faction',
  text: 'faction',
  related: {
    type: { search: [{ type: 'faction_type'}] },
    trait: { search: [{ type: 'faction_trait'}] },
    goal: { search: [{ type: 'faction_goal'}] },
  },
};

const factionType: IElementDefinition = {
  type: 'faction_type',
  text: 'faction_type',
  options: [{
    type: 'faction_type',
    text: 'faction_type_1',
  }, {
    type: 'faction_type',
    text: 'faction_type_2',
  }, {
    type: 'faction_type',
    text: 'faction_type_3',
  }, {
    type: 'faction_type',
    text: 'faction_type_4',
  }, {
    type: 'faction_type',
    text: 'faction_type_5',
  }, {
    type: 'faction_type',
    text: 'faction_type_6',
  }, {
    type: 'faction_type',
    text: 'faction_type_7',
  }, {
    type: 'faction_type',
    text: 'faction_type_8',
  }, {
    type: 'faction_type',
    text: 'faction_type_9',
  }, {
    type: 'faction_type',
    text: 'faction_type_10',
  }, {
    type: 'faction_type',
    text: 'faction_type_11',
  }, {
    type: 'faction_type',
    text: 'faction_type_12',
  }, {
    type: 'faction_type',
    text: 'faction_type_13',
  }, {
    type: 'faction_type',
    text: 'faction_type_14',
  }, {
    type: 'faction_type',
    text: 'faction_type_15',
  }, {
    type: 'faction_type',
    text: 'faction_type_16',
  }, {
    type: 'faction_type',
    text: 'faction_type_17',
  }, {
    type: 'faction_type',
    text: 'faction_type_18',
  }, {
    type: 'faction_type',
    text: 'faction_type_19',
  }, {
    type: 'faction_type',
    text: 'faction_type_20',
  }, {
    type: 'faction_type',
    text: 'faction_type_21',
  }, {
    type: 'faction_type',
    text: 'faction_type_22',
  }, {
    type: 'faction_type',
    text: 'faction_type_23',
  }, {
    type: 'faction_type',
    text: 'faction_type_24',
  }, {
    type: 'faction_type',
    text: 'faction_type_25',
  }, {
    type: 'faction_type',
    text: 'faction_type_26',
  }, {
    type: 'faction_type',
    text: 'faction_type_27',
  }, {
    type: 'faction_type',
    text: 'faction_type_28',
  }, {
    type: 'faction_type',
    text: 'faction_type_29',
  }, {
    type: 'faction_type',
    text: 'faction_type_30',
  }, {
    type: 'faction_type',
    text: 'faction_type_31',
  }, {
    type: 'faction_type',
    text: 'faction_type_32',
  }, {
    type: 'faction_type',
    text: 'faction_type_33',
  }, {
    type: 'faction_type',
    text: 'faction_type_34',
  }, {
    type: 'faction_type',
    text: 'faction_type_35',
  }, {
    type: 'faction_type',
    text: 'faction_type_36',
  }],
};

const factionTrait: IElementDefinition = {
  type: 'faction_trait',
  text: 'faction_trait',
  options: [{
    type: 'faction_trait',
    text: 'faction_trait_1',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_2',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_3',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_4',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_5',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_6',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_7',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_8',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_9',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_10',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_11',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_12',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_13',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_14',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_15',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_16',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_17',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_18',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_19',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_20',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_21',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_22',
    related: { personality: { search: [{ type: 'personality' }] } },
  }, {
    type: 'faction_trait',
    text: 'faction_trait_23',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_24',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_25',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_26',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_27',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_28',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_29',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_30',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_31',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_32',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_33',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_34',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_35',
  }, {
    type: 'faction_trait',
    text: 'faction_trait_36',
  }],
};

const factionGoal: IElementDefinition = {
  type: 'faction_goal',
  text: 'faction_goal',
  options: [{
    type: 'faction_goal',
    text: 'faction_goal_1',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_2',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_3',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_4',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_5',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_6',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_7',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_8',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_9',
    related: { monster: { search: [{ type: 'monster' }] } },
  }, {
    type: 'faction_goal',
    text: 'faction_goal_10',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'faction_goal',
    text: 'faction_goal_11',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_12',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_13',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_14',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_15',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_16',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_17',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_18',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'faction_goal',
    text: 'faction_goal_19',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_20',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_21',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_22',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_23',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_24',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_25',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_26',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_27',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_28',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_29',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_30',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_31',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_32',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_33',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_34',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'faction_goal',
    text: 'faction_goal_35',
  }, {
    type: 'faction_goal',
    text: 'faction_goal_36',
  }],
};

export {
  faction,
  factionGoal,
  factionTrait,
  factionType,
};
