import { ERandomOption, IElementDefinition } from '../typings';

const inn: IElementDefinition = {
  type: 'inn',
  text: 'inn',
  related: {
    adjective: { search: [{ type: 'inn_adjective' }] },
    name: { search: [{ type: 'inn_name' }] },
    quirk: { search: [{ type: 'inn_quirk' }] },
  },
};

const innAdjective: IElementDefinition = {
  type: 'inn_adjective',
  text: 'inn_adjective',
  options: [{
    type: 'inn_adjective',
    text: 'inn_adjective_1',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_2',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_3',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_4',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_5',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_6',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_7',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_8',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_9',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_10',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_11',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_12',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_13',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_14',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_15',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_16',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_17',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_18',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_19',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_20',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_21',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_22',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_23',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_24',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_25',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_26',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_27',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_28',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_29',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_30',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_31',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_32',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_33',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_34',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_35',
  }, {
    type: 'inn_adjective',
    text: 'inn_adjective_36',
  }],
};

const innName: IElementDefinition = {
  type: 'inn_name',
  text: 'inn_name',
  options: [{
    type: 'inn_name',
    text: 'inn_name_1',
  }, {
    type: 'inn_name',
    text: 'inn_name_2',
  }, {
    type: 'inn_name',
    text: 'inn_name_3',
  }, {
    type: 'inn_name',
    text: 'inn_name_4',
  }, {
    type: 'inn_name',
    text: 'inn_name_5',
  }, {
    type: 'inn_name',
    text: 'inn_name_6',
  }, {
    type: 'inn_name',
    text: 'inn_name_7',
  }, {
    type: 'inn_name',
    text: 'inn_name_8',
  }, {
    type: 'inn_name',
    text: 'inn_name_9',
  }, {
    type: 'inn_name',
    text: 'inn_name_10',
  }, {
    type: 'inn_name',
    text: 'inn_name_11',
  }, {
    type: 'inn_name',
    text: 'inn_name_12',
  }, {
    type: 'inn_name',
    text: 'inn_name_13',
  }, {
    type: 'inn_name',
    text: 'inn_name_14',
  }, {
    type: 'inn_name',
    text: 'inn_name_15',
  }, {
    type: 'inn_name',
    text: 'inn_name_16',
  }, {
    type: 'inn_name',
    text: 'inn_name_17',
  }, {
    type: 'inn_name',
    text: 'inn_name_18',
  }, {
    type: 'inn_name',
    text: 'inn_name_19',
  }, {
    type: 'inn_name',
    text: 'inn_name_20',
  }, {
    type: 'inn_name',
    text: 'inn_name_21',
  }, {
    type: 'inn_name',
    text: 'inn_name_22',
  }, {
    type: 'inn_name',
    text: 'inn_name_23',
  }, {
    type: 'inn_name',
    text: 'inn_name_24',
  }, {
    type: 'inn_name',
    text: 'inn_name_25',
  }, {
    type: 'inn_name',
    text: 'inn_name_26',
  }, {
    type: 'inn_name',
    text: 'inn_name_27',
  }, {
    type: 'inn_name',
    text: 'inn_name_28',
  }, {
    type: 'inn_name',
    text: 'inn_name_29',
  }, {
    type: 'inn_name',
    text: 'inn_name_30',
  }, {
    type: 'inn_name',
    text: 'inn_name_31',
  }, {
    type: 'inn_name',
    text: 'inn_name_32',
  }, {
    type: 'inn_name',
    text: 'inn_name_33',
  }, {
    type: 'inn_name',
    text: 'inn_name_34',
  }, {
    type: 'inn_name',
    text: 'inn_name_35',
  }, {
    type: 'inn_name',
    text: 'inn_name_36',
  }],
};

const innQuirk: IElementDefinition = {
  type: 'inn_quirk',
  text: 'inn_quirk',
  options: [{
    type: 'inn_quirk',
    text: 'inn_quirk_1',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_2',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_3',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_4',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_5',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_6',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_7',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_8',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_9',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_10',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_11',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_12',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_13',
    related: { dungeon_layout: { search: [{ type: 'dungeon_layout' }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_14',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_15',
    related: { faction: { search: [{ type: 'faction', random: ERandomOption.all }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_16',
    related: { faction_trait: { search: [{ type: 'faction_trait' }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_17',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_18',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_19',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_20',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_21',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_22',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_23',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_24',
    related: { city_building: { search: [{ type: 'city_building' }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_25',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_26',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_27',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_28',
    related: { npc: { search: [{ type: 'npc', random: ERandomOption.all }] } },
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_29',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_30',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_31',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_32',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_33',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_34',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_35',
  }, {
    type: 'inn_quirk',
    text: 'inn_quirk_36',
  }],
};

export {
  inn,
  innAdjective,
  innName,
  innQuirk,
};
