import { IElementDefinition } from '../typings';

const miscellaneousItem: IElementDefinition = {
  type: 'miscellaneous_item',
  text: 'miscellaneous_item',
  options: [{
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_1',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_2',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_3',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_4',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_5',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_6',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_7',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_8',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_9',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_10',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_11',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_12',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_13',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_14',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_15',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_16',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_17',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_18',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_19',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_20',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_21',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_22',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_23',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_24',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_24',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_26',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_27',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_28',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_29',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_30',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_31',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_32',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_33',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_34',
  }, {
    type: 'miscellaneous_item',
    text: 'miscellaneous_item_35',
  }],
};

const wornItem: IElementDefinition = {
  type: 'worn_items',
  text: 'worn_items',
  options: [{
    type: 'worn_items',
    text: 'worn_items_1',
  }, {
    type: 'worn_items',
    text: 'worn_items_2',
  }, {
    type: 'worn_items',
    text: 'worn_items_3',
  }, {
    type: 'worn_items',
    text: 'worn_items_4',
  }, {
    type: 'worn_items',
    text: 'worn_items_5',
  }, {
    type: 'worn_items',
    text: 'worn_items_6',
  }, {
    type: 'worn_items',
    text: 'worn_items_7',
  }, {
    type: 'worn_items',
    text: 'worn_items_8',
  }, {
    type: 'worn_items',
    text: 'worn_items_9',
  }, {
    type: 'worn_items',
    text: 'worn_items_10',
  }, {
    type: 'worn_items',
    text: 'worn_items_11',
  }, {
    type: 'worn_items',
    text: 'worn_items_12',
  }, {
    type: 'worn_items',
    text: 'worn_items_13',
  }, {
    type: 'worn_items',
    text: 'worn_items_14',
  }, {
    type: 'worn_items',
    text: 'worn_items_15',
  }, {
    type: 'worn_items',
    text: 'worn_items_16',
  }, {
    type: 'worn_items',
    text: 'worn_items_17',
  }, {
    type: 'worn_items',
    text: 'worn_items_18',
  }, {
    type: 'worn_items',
    text: 'worn_items_19',
  }, {
    type: 'worn_items',
    text: 'worn_items_20',
  }, {
    type: 'worn_items',
    text: 'worn_items_21',
  }, {
    type: 'worn_items',
    text: 'worn_items_22',
  }, {
    type: 'worn_items',
    text: 'worn_items_23',
  }, {
    type: 'worn_items',
    text: 'worn_items_24',
  }, {
    type: 'worn_items',
    text: 'worn_items_24',
  }, {
    type: 'worn_items',
    text: 'worn_items_26',
  }, {
    type: 'worn_items',
    text: 'worn_items_27',
  }, {
    type: 'worn_items',
    text: 'worn_items_28',
  }, {
    type: 'worn_items',
    text: 'worn_items_29',
  }, {
    type: 'worn_items',
    text: 'worn_items_30',
  }, {
    type: 'worn_items',
    text: 'worn_items_31',
  }, {
    type: 'worn_items',
    text: 'worn_items_32',
  }, {
    type: 'worn_items',
    text: 'worn_items_33',
  }, {
    type: 'worn_items',
    text: 'worn_items_34',
  }, {
    type: 'worn_items',
    text: 'worn_items_35',
  }],
};

const weaponItem: IElementDefinition = {
  type: 'weapon_item',
  text: 'weapon_item',
  options: [{
    type: 'weapon_item',
    text: 'weapon_item_1',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_2',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_3',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_4',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_5',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_6',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_7',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_8',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_9',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_10',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_11',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_12',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_13',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_14',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_15',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_16',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_17',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_18',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_19',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_20',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_21',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_22',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_23',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_24',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_24',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_26',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_27',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_28',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_29',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_30',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_31',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_32',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_33',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_34',
  }, {
    type: 'weapon_item',
    text: 'weapon_item_35',
  }],
};

const toolItem: IElementDefinition = {
  type: 'tool_item',
  text: 'tool_item',
  options: [{
    type: 'tool_item',
    text: 'tool_item_1',
  }, {
    type: 'tool_item',
    text: 'tool_item_2',
  }, {
    type: 'tool_item',
    text: 'tool_item_3',
  }, {
    type: 'tool_item',
    text: 'tool_item_4',
  }, {
    type: 'tool_item',
    text: 'tool_item_5',
  }, {
    type: 'tool_item',
    text: 'tool_item_6',
  }, {
    type: 'tool_item',
    text: 'tool_item_7',
  }, {
    type: 'tool_item',
    text: 'tool_item_8',
  }, {
    type: 'tool_item',
    text: 'tool_item_9',
  }, {
    type: 'tool_item',
    text: 'tool_item_10',
  }, {
    type: 'tool_item',
    text: 'tool_item_11',
  }, {
    type: 'tool_item',
    text: 'tool_item_12',
  }, {
    type: 'tool_item',
    text: 'tool_item_13',
  }, {
    type: 'tool_item',
    text: 'tool_item_14',
  }, {
    type: 'tool_item',
    text: 'tool_item_15',
  }, {
    type: 'tool_item',
    text: 'tool_item_16',
  }, {
    type: 'tool_item',
    text: 'tool_item_17',
  }, {
    type: 'tool_item',
    text: 'tool_item_18',
  }, {
    type: 'tool_item',
    text: 'tool_item_19',
  }, {
    type: 'tool_item',
    text: 'tool_item_20',
  }, {
    type: 'tool_item',
    text: 'tool_item_21',
  }, {
    type: 'tool_item',
    text: 'tool_item_22',
  }, {
    type: 'tool_item',
    text: 'tool_item_23',
  }, {
    type: 'tool_item',
    text: 'tool_item_24',
  }, {
    type: 'tool_item',
    text: 'tool_item_24',
  }, {
    type: 'tool_item',
    text: 'tool_item_26',
  }, {
    type: 'tool_item',
    text: 'tool_item_27',
  }, {
    type: 'tool_item',
    text: 'tool_item_28',
  }, {
    type: 'tool_item',
    text: 'tool_item_29',
  }, {
    type: 'tool_item',
    text: 'tool_item_30',
  }, {
    type: 'tool_item',
    text: 'tool_item_31',
  }, {
    type: 'tool_item',
    text: 'tool_item_32',
  }, {
    type: 'tool_item',
    text: 'tool_item_33',
  }, {
    type: 'tool_item',
    text: 'tool_item_34',
  }, {
    type: 'tool_item',
    text: 'tool_item_35',
  }],
};

const treasure: IElementDefinition = {
  type: 'treasure',
  text: 'treasure',
  related: {
    item: { search: [{ type: 'treasure_item' }] },
    trait: { search: [{ type: 'treasure_trait' }] },
  },
};

const treasureItem: IElementDefinition = {
  type: 'treasure_item',
  text: 'treasure_item',
  options: [{
    type: 'treasure_item',
    text: 'treasure_item_1',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_2',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_3',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_4',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_5',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_6',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_7',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_8',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_9',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_10',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_11',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_12',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_13',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_14',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_15',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_16',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_17',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_18',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_19',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_20',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_21',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_22',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_23',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_24',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_25',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_26',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_27',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_28',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_29',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_30',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_31',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_32',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_33',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_34',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_35',
  }, {
    type: 'treasure_item',
    text: 'treasure_item_36',
  }],
};

const valuableMaterial: IElementDefinition = {
  type: 'valuable_material',
  text: 'valuable_material',
  options: [{
    type: 'valuable_material',
    text: 'valuable_material_1',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_2',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_3',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_4',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_5',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_6',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_7',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_8',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_9',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_10',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_11',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_12',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_13',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_14',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_15',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_16',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_17',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_18',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_19',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_20',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_21',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_22',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_23',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_24',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_25',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_26',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_27',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_28',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_29',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_30',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_31',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_32',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_33',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_34',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_35',
  }, {
    type: 'valuable_material',
    text: 'valuable_material_36',
  }],
};

const treasureTrait: IElementDefinition = {
  type: 'treasure_trait',
  text: 'treasure_trait',
  options: [{
    type: 'treasure_trait',
    text: 'treasure_trait_1',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_2',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_3',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_4',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_5',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_6',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_7',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_8',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_9',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_10',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_11',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_12',
    related: { effects: { search: [{ type: 'effects' }] } },
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_13',
    related: { element: { search: [{ type: 'element' }] } },
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_14',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_15',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_16',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_17',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_18',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_19',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_20',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_21',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_22',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_23',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_24',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_25',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_26',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_27',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_28',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_29',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_30',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_31',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_32',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_33',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_34',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_35',
  }, {
    type: 'treasure_trait',
    text: 'treasure_trait_36',
  }],
};

export {
  miscellaneousItem,
  wornItem,
  weaponItem,
  toolItem,
  treasure,
  treasureItem,
  treasureTrait,
  valuableMaterial,
};
