import { ERandomOption, IElementDefinition } from '../typings';

const pj: IElementDefinition = {
  type: 'pj',
  text: 'pj',
  related: {
    appearance: {
      search: [{
        type: 'appearance',
        random: ERandomOption.random,
      }],
    },
    physical: {
      search: [{
        type: 'pj_physical',
        random: ERandomOption.random,
      }],
    },
    clothes: {
      search: [{
        type: 'clothes',
        random: ERandomOption.random,
      }],
    },
    background: {
      search: [{
        type: 'background',
        random: ERandomOption.random,
      }],
    },
    mannerism: {
      search: [{
        type: 'mannerism',
        random: ERandomOption.random,
      }],
    },
    personality: {
      search: [{
        type: 'personality',
        random: ERandomOption.random,
      }],
    },
  },
};

const appearance: IElementDefinition = {
  type: 'appearance',
  text: 'appearance',
  options: [{
    type: 'appearance',
    text: 'appearance_1',
  }, {
    type: 'appearance',
    text: 'appearance_2',
  }, {
    type: 'appearance',
    text: 'appearance_3',
  }, {
    type: 'appearance',
    text: 'appearance_4',
  }, {
    type: 'appearance',
    text: 'appearance_5',
  }, {
    type: 'appearance',
    text: 'appearance_6',
  }, {
    type: 'appearance',
    text: 'appearance_7',
  }, {
    type: 'appearance',
    text: 'appearance_8',
  }, {
    type: 'appearance',
    text: 'appearance_9',
  }, {
    type: 'appearance',
    text: 'appearance_10',
  }, {
    type: 'appearance',
    text: 'appearance_11',
  }, {
    type: 'appearance',
    text: 'appearance_12',
  }, {
    type: 'appearance',
    text: 'appearance_13',
  }, {
    type: 'appearance',
    text: 'appearance_14',
  }, {
    type: 'appearance',
    text: 'appearance_15',
  }, {
    type: 'appearance',
    text: 'appearance_16',
  }, {
    type: 'appearance',
    text: 'appearance_17',
  }, {
    type: 'appearance',
    text: 'appearance_18',
  }, {
    type: 'appearance',
    text: 'appearance_19',
  }, {
    type: 'appearance',
    text: 'appearance_20',
  }, {
    type: 'appearance',
    text: 'appearance_21',
  }, {
    type: 'appearance',
    text: 'appearance_22',
  }, {
    type: 'appearance',
    text: 'appearance_23',
  }, {
    type: 'appearance',
    text: 'appearance_24',
  }, {
    type: 'appearance',
    text: 'appearance_25',
  }, {
    type: 'appearance',
    text: 'appearance_26',
  }, {
    type: 'appearance',
    text: 'appearance_27',
  }, {
    type: 'appearance',
    text: 'appearance_28',
  }, {
    type: 'appearance',
    text: 'appearance_29',
  }, {
    type: 'appearance',
    text: 'appearance_30',
  }, {
    type: 'appearance',
    text: 'appearance_31',
  }, {
    type: 'appearance',
    text: 'appearance_32',
  }, {
    type: 'appearance',
    text: 'appearance_33',
  }, {
    type: 'appearance',
    text: 'appearance_34',
  }, {
    type: 'appearance',
    text: 'appearance_35',
  }, {
    type: 'appearance',
    text: 'appearance_36',
  }],
};

const pjPhysical: IElementDefinition = {
  type: 'pj_physical',
  text: 'pj_physical',
  options: [{
    type: 'pj_physical',
    text: 'pj_physical_1',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_2',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_3',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_4',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_5',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_6',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_7',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_8',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_9',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_10',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_11',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_12',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_13',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_14',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_15',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_16',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_17',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_18',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_19',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_20',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_21',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_22',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_23',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_24',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_25',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_26',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_27',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_28',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_29',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_30',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_31',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_32',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_33',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_34',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_35',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_36',
  }],
};

const background: IElementDefinition = {
  type: 'background',
  text: 'background',
  options: [{
    type: 'background',
    text: 'background_1',
  }, {
    type: 'background',
    text: 'background_2',
  }, {
    type: 'background',
    text: 'background_3',
  }, {
    type: 'background',
    text: 'background_4',
  }, {
    type: 'background',
    text: 'background_5',
  }, {
    type: 'background',
    text: 'background_6',
  }, {
    type: 'background',
    text: 'background_7',
  }, {
    type: 'background',
    text: 'background_8',
  }, {
    type: 'background',
    text: 'background_9',
  }, {
    type: 'background',
    text: 'background_10',
  }, {
    type: 'background',
    text: 'background_11',
  }, {
    type: 'background',
    text: 'background_12',
  }, {
    type: 'background',
    text: 'background_13',
  }, {
    type: 'background',
    text: 'background_14',
  }, {
    type: 'background',
    text: 'background_15',
  }, {
    type: 'background',
    text: 'background_16',
  }, {
    type: 'background',
    text: 'background_17',
  }, {
    type: 'background',
    text: 'background_18',
  }, {
    type: 'background',
    text: 'background_19',
  }, {
    type: 'background',
    text: 'background_20',
  }, {
    type: 'background',
    text: 'background_21',
  }, {
    type: 'background',
    text: 'background_22',
  }, {
    type: 'background',
    text: 'background_23',
  }, {
    type: 'background',
    text: 'background_24',
  }, {
    type: 'background',
    text: 'background_25',
  }, {
    type: 'background',
    text: 'background_26',
  }, {
    type: 'background',
    text: 'background_27',
  }, {
    type: 'background',
    text: 'background_28',
  }, {
    type: 'background',
    text: 'background_29',
  }, {
    type: 'background',
    text: 'background_30',
  }, {
    type: 'background',
    text: 'background_31',
  }, {
    type: 'background',
    text: 'background_32',
  }, {
    type: 'background',
    text: 'background_33',
  }, {
    type: 'background',
    text: 'background_34',
  }, {
    type: 'background',
    text: 'background_35',
  }, {
    type: 'background',
    text: 'background_36',
  }],
};

const personality: IElementDefinition = {
  type: 'personality',
  text: 'personality',
  options: [{
    type: 'personality',
    text: 'personality_1',
  }, {
    type: 'personality',
    text: 'personality_2',
  }, {
    type: 'personality',
    text: 'personality_3',
  }, {
    type: 'personality',
    text: 'personality_4',
  }, {
    type: 'personality',
    text: 'personality_5',
  }, {
    type: 'personality',
    text: 'personality_6',
  }, {
    type: 'personality',
    text: 'personality_7',
  }, {
    type: 'personality',
    text: 'personality_8',
  }, {
    type: 'personality',
    text: 'personality_9',
  }, {
    type: 'personality',
    text: 'personality_10',
  }, {
    type: 'personality',
    text: 'personality_11',
  }, {
    type: 'personality',
    text: 'personality_12',
  }, {
    type: 'personality',
    text: 'personality_13',
  }, {
    type: 'personality',
    text: 'personality_14',
  }, {
    type: 'personality',
    text: 'personality_15',
  }, {
    type: 'personality',
    text: 'personality_16',
  }, {
    type: 'personality',
    text: 'personality_17',
  }, {
    type: 'personality',
    text: 'personality_18',
  }, {
    type: 'personality',
    text: 'personality_19',
  }, {
    type: 'personality',
    text: 'personality_20',
  }, {
    type: 'personality',
    text: 'personality_21',
  }, {
    type: 'personality',
    text: 'personality_22',
  }, {
    type: 'personality',
    text: 'personality_23',
  }, {
    type: 'personality',
    text: 'personality_24',
  }, {
    type: 'personality',
    text: 'personality_25',
  }, {
    type: 'personality',
    text: 'personality_26',
  }, {
    type: 'personality',
    text: 'personality_27',
  }, {
    type: 'personality',
    text: 'personality_28',
  }, {
    type: 'personality',
    text: 'personality_29',
  }, {
    type: 'personality',
    text: 'personality_30',
  }, {
    type: 'personality',
    text: 'personality_31',
  }, {
    type: 'personality',
    text: 'personality_32',
  }, {
    type: 'personality',
    text: 'personality_33',
  }, {
    type: 'personality',
    text: 'personality_34',
  }, {
    type: 'personality',
    text: 'personality_35',
  }, {
    type: 'personality',
    text: 'personality_36',
  }],
};

const clothes: IElementDefinition = {
  type: 'clothes',
  text: 'clothes',
  options: [{
    type: 'clothes',
    text: 'clothes_1',
  }, {
    type: 'clothes',
    text: 'clothes_2',
  }, {
    type: 'clothes',
    text: 'clothes_3',
  }, {
    type: 'clothes',
    text: 'clothes_4',
  }, {
    type: 'clothes',
    text: 'clothes_5',
  }, {
    type: 'clothes',
    text: 'clothes_6',
  }, {
    type: 'clothes',
    text: 'clothes_7',
  }, {
    type: 'clothes',
    text: 'clothes_8',
  }, {
    type: 'clothes',
    text: 'clothes_9',
  }, {
    type: 'clothes',
    text: 'clothes_10',
  }, {
    type: 'clothes',
    text: 'clothes_11',
  }, {
    type: 'clothes',
    text: 'clothes_12',
  }, {
    type: 'clothes',
    text: 'clothes_13',
  }, {
    type: 'clothes',
    text: 'clothes_14',
  }, {
    type: 'clothes',
    text: 'clothes_15',
  }, {
    type: 'clothes',
    text: 'clothes_16',
  }, {
    type: 'clothes',
    text: 'clothes_17',
  }, {
    type: 'clothes',
    text: 'clothes_18',
  }, {
    type: 'clothes',
    text: 'clothes_19',
  }, {
    type: 'clothes',
    text: 'clothes_20',
  }, {
    type: 'clothes',
    text: 'clothes_21',
  }, {
    type: 'clothes',
    text: 'clothes_22',
  }, {
    type: 'clothes',
    text: 'clothes_23',
  }, {
    type: 'clothes',
    text: 'clothes_24',
  }, {
    type: 'clothes',
    text: 'clothes_25',
  }, {
    type: 'clothes',
    text: 'clothes_26',
  }, {
    type: 'clothes',
    text: 'clothes_27',
  }, {
    type: 'clothes',
    text: 'clothes_28',
  }, {
    type: 'clothes',
    text: 'clothes_29',
  }, {
    type: 'clothes',
    text: 'clothes_30',
  }, {
    type: 'clothes',
    text: 'clothes_31',
  }, {
    type: 'clothes',
    text: 'clothes_32',
  }, {
    type: 'clothes',
    text: 'clothes_33',
  }, {
    type: 'clothes',
    text: 'clothes_34',
  }, {
    type: 'clothes',
    text: 'clothes_35',
  }, {
    type: 'clothes',
    text: 'clothes_36',
  }],
};

const mannerism: IElementDefinition = {
  type: 'mannerism',
  text: 'mannerism',
  options: [{
    type: 'mannerism',
    text: 'mannerism_1',
  }, {
    type: 'mannerism',
    text: 'mannerism_2',
  }, {
    type: 'mannerism',
    text: 'mannerism_3',
  }, {
    type: 'mannerism',
    text: 'mannerism_4',
  }, {
    type: 'mannerism',
    text: 'mannerism_5',
  }, {
    type: 'mannerism',
    text: 'mannerism_6',
  }, {
    type: 'mannerism',
    text: 'mannerism_7',
  }, {
    type: 'mannerism',
    text: 'mannerism_8',
  }, {
    type: 'mannerism',
    text: 'mannerism_9',
  }, {
    type: 'mannerism',
    text: 'mannerism_10',
  }, {
    type: 'mannerism',
    text: 'mannerism_11',
  }, {
    type: 'mannerism',
    text: 'mannerism_12',
  }, {
    type: 'mannerism',
    text: 'mannerism_13',
  }, {
    type: 'mannerism',
    text: 'mannerism_14',
  }, {
    type: 'mannerism',
    text: 'mannerism_15',
  }, {
    type: 'mannerism',
    text: 'mannerism_16',
  }, {
    type: 'mannerism',
    text: 'mannerism_17',
  }, {
    type: 'mannerism',
    text: 'mannerism_18',
  }, {
    type: 'mannerism',
    text: 'mannerism_19',
  }, {
    type: 'mannerism',
    text: 'mannerism_20',
  }, {
    type: 'mannerism',
    text: 'mannerism_21',
  }, {
    type: 'mannerism',
    text: 'mannerism_22',
  }, {
    type: 'mannerism',
    text: 'mannerism_23',
  }, {
    type: 'mannerism',
    text: 'mannerism_24',
  }, {
    type: 'mannerism',
    text: 'mannerism_25',
  }, {
    type: 'mannerism',
    text: 'mannerism_26',
  }, {
    type: 'mannerism',
    text: 'mannerism_27',
  }, {
    type: 'mannerism',
    text: 'mannerism_28',
  }, {
    type: 'mannerism',
    text: 'mannerism_29',
  }, {
    type: 'mannerism',
    text: 'mannerism_30',
  }, {
    type: 'mannerism',
    text: 'mannerism_31',
  }, {
    type: 'mannerism',
    text: 'mannerism_32',
  }, {
    type: 'mannerism',
    text: 'mannerism_33',
  }, {
    type: 'mannerism',
    text: 'mannerism_34',
  }, {
    type: 'mannerism',
    text: 'mannerism_35',
  }, {
    type: 'mannerism',
    text: 'mannerism_36',
  }],
};

export {
  pj,
  appearance,
  personality,
  pjPhysical,
  background,
  mannerism,
  clothes,
};
