import { ERandomOption, IElementDefinition } from '../typings';

const plant: IElementDefinition = {
  type: 'plant',
  text: 'plant',
  options: [{
    type: 'plant',
    text: 'edible_plant',
    related: {
      edible_plant: { search: [{ type: 'edible_plant' }] },
    },
  }, {
    type: 'plant',
    text: 'poisonous_plant',
    related: {
      poisonous_plant: { search: [{ type: 'poisonous_plant' }] },
    },
  }],
};

const ediblePlant: IElementDefinition = {
  type: 'edible_plant',
  text: 'edible_plant',
  options: [{
    type: 'edible_plant',
    text: 'edible_plant_1',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_2',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_3',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_4',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_5',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_6',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_7',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_8',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_9',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_10',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_11',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_12',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_13',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_14',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_15',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_16',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_17',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_18',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_19',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_20',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_21',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_22',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_23',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_24',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_25',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_26',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_27',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_28',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_29',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_30',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_31',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_32',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_33',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_34',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_35',
  }, {
    type: 'edible_plant',
    text: 'edible_plant_36',
  }],
};

const poisonousPlant: IElementDefinition = {
  type: 'poisonous_plant',
  text: 'poisonous_plant',
  options: [{
    type: 'poisonous_plant',
    text: 'poisonous_plant_1',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_2',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_3',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_4',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_5',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_6',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_7',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_8',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_9',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_10',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_11',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_12',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_13',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_14',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_15',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_16',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_17',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_18',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_19',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_20',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_21',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_22',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_23',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_24',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_25',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_26',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_27',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_28',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_29',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_30',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_31',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_32',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_33',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_34',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_35',
  }, {
    type: 'poisonous_plant',
    text: 'poisonous_plant_36',
  }],
};

export {
  plant,
  ediblePlant,
  poisonousPlant,
};
