import { ERandomOption, IElementDefinition } from '../typings';

// const trap: IElementDefinition = {
//   type: 'trap',
//   text: 'trap',
//   related: {
//     effect: { search: [{ type: 'trap_effect'}] },
//     trigger: { search: [{ type: 'trap_trigger'}] },
//   },
// };

const wildRegion: IElementDefinition = {
  type: 'wild_region',
  text: 'wild_region',
  options: [{
    type: 'wild_region',
    text: 'wild_region_1',
  }, {
    type: 'wild_region',
    text: 'wild_region_2',
  }, {
    type: 'wild_region',
    text: 'wild_region_3',
  }, {
    type: 'wild_region',
    text: 'wild_region_4',
  }, {
    type: 'wild_region',
    text: 'wild_region_5',
  }, {
    type: 'wild_region',
    text: 'wild_region_6',
  }, {
    type: 'wild_region',
    text: 'wild_region_7',
  }, {
    type: 'wild_region',
    text: 'wild_region_8',
  }, {
    type: 'wild_region',
    text: 'wild_region_9',
  }, {
    type: 'wild_region',
    text: 'wild_region_10',
  }, {
    type: 'wild_region',
    text: 'wild_region_11',
  }, {
    type: 'wild_region',
    text: 'wild_region_12',
  }, {
    type: 'wild_region',
    text: 'wild_region_13',
  }, {
    type: 'wild_region',
    text: 'wild_region_14',
  }, {
    type: 'wild_region',
    text: 'wild_region_15',
  }, {
    type: 'wild_region',
    text: 'wild_region_16',
  }, {
    type: 'wild_region',
    text: 'wild_region_17',
  }, {
    type: 'wild_region',
    text: 'wild_region_18',
  }, {
    type: 'wild_region',
    text: 'wild_region_19',
  }, {
    type: 'wild_region',
    text: 'wild_region_20',
  }, {
    type: 'wild_region',
    text: 'wild_region_21',
  }, {
    type: 'wild_region',
    text: 'wild_region_22',
  }, {
    type: 'wild_region',
    text: 'wild_region_23',
  }, {
    type: 'wild_region',
    text: 'wild_region_24',
  }, {
    type: 'wild_region',
    text: 'wild_region_25',
  }, {
    type: 'wild_region',
    text: 'wild_region_26',
  }, {
    type: 'wild_region',
    text: 'wild_region_27',
  }, {
    type: 'wild_region',
    text: 'wild_region_28',
  }, {
    type: 'wild_region',
    text: 'wild_region_29',
  }, {
    type: 'wild_region',
    text: 'wild_region_30',
  }, {
    type: 'wild_region',
    text: 'wild_region_31',
  }, {
    type: 'wild_region',
    text: 'wild_region_32',
  }, {
    type: 'wild_region',
    text: 'wild_region_33',
  }, {
    type: 'wild_region',
    text: 'wild_region_34',
  }, {
    type: 'wild_region',
    text: 'wild_region_35',
  }, {
    type: 'wild_region',
    text: 'wild_region_36',
  }],
};

const wildLandmark: IElementDefinition = {
  type: 'wild_landmark',
  text: 'wild_landmark',
  options: [{
    type: 'wild_landmark',
    text: 'wild_landmark_1',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_2',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_3',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_4',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_5',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_6',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_7',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_8',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_9',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_10',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_11',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_12',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_13',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_14',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_15',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_16',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_17',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_18',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_19',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_20',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_21',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_22',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_23',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_24',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_25',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_26',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_27',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_28',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_29',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_30',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_31',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_32',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_33',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_34',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_35',
  }, {
    type: 'wild_landmark',
    text: 'wild_landmark_36',
  }],
};

const wildStructure: IElementDefinition = {
  type: 'wild_structure',
  text: 'wild_structure',
  options: [{
    type: 'wild_structure',
    text: 'wild_structure_1',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_2',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_3',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_4',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_5',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_6',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_7',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_8',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_9',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_10',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_11',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_12',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_13',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_14',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_15',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_16',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_17',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_18',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_19',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_20',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_21',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_22',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_23',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_24',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_25',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_26',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_27',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_28',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_29',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_30',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_31',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_32',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_33',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_34',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_35',
  }, {
    type: 'wild_structure',
    text: 'wild_structure_36',
  }],
};

const wildTrait: IElementDefinition = {
  type: 'wild_trait',
  text: 'wild_trait',
  options: [{
    type: 'wild_trait',
    text: 'wild_trait_1',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_2',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_3',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_4',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_5',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_6',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_7',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_8',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_9',
    related: { dungeon_ruination: { search: [{ type: 'dungeon_ruination' }] } },
  }, {
    type: 'wild_trait',
    text: 'wild_trait_10',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_11',
    related: { ethereal_effect: { search: [{ type: 'ethereal_effect' }] } },
  }, {
    type: 'wild_trait',
    text: 'wild_trait_12',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_13',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_14',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_15',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_16',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_17',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_18',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_19',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_20',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_21',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_22',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_23',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_24',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_25',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_26',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_27',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_28',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_29',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_30',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_31',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_32',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_33',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_34',
    related: { physical_effect: { search: [{ type: 'physical_effect' }] } },
  }, {
    type: 'wild_trait',
    text: 'wild_trait_35',
  }, {
    type: 'wild_trait',
    text: 'wild_trait_36',
  }],
};

const wildDiscovery: IElementDefinition = {
  type: 'wild_discovery',
  text: 'wild_discovery',
  options: [{
    type: 'wild_discovery',
    text: 'wild_discovery_1',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_2',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_3',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_4',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_5',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_6',
    related: { npc_civilized: { search: [{ type: 'npc_civilized' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_7',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_8',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_9',
    related: { dungeon_activty: { search: [{ type: 'dungeon_activty' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_10',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_11',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_12',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_13',
    related: { item: { search: [{ type: 'item' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_14',
    related: { npc: { search: [{ type: 'npc', random: ERandomOption.all }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_15',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_16',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_17',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_18',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_19',
    related: { mutation: { search: [{ type: 'mutation' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_20',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_21',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_22',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_23',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_24',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_25',
    related: { npc: { search: [{ type: 'npc', random: ERandomOption.all }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_26',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_27',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_28',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_29',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_30',
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_31',
    related: { npc_underworld: { search: [{ type: 'npc_underworld' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_32',
    related: { wild_landmark: { search: [{ type: 'wild_landmark' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_33',
    related: { wild_structure: { search: [{ type: 'wild_structure' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_34',
    related: { npc_wilderness: { search: [{ type: 'npc_wilderness' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_35',
    related: { wild_activity: { search: [{ type: 'wild_activity' }] } },
  }, {
    type: 'wild_discovery',
    text: 'wild_discovery_36',
  }],
};

const wildActivity: IElementDefinition = {
  type: 'wild_activity',
  text: 'wild_activity',
  options: [{
    type: 'wild_activity',
    text: 'wild_activity_1',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_2',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_3',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_4',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_5',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_6',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_7',
    related: { city_activity: { search: [{ type: 'city_activity' }] } },
  }, {
    type: 'wild_activity',
    text: 'wild_activity_8',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_9',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_10',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_11',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_12',
    related: { dungeon_activity: { search: [{ type: 'dungeon_activity' }] } },
  }, {
    type: 'wild_activity',
    text: 'wild_activity_13',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_14',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_15',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_16',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_17',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_18',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_19',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_20',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_21',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_22',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_23',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_24',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_25',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_26',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_27',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_28',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_29',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_30',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_31',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_32',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_33',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_34',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_35',
  }, {
    type: 'wild_activity',
    text: 'wild_activity_36',
  }],
};

const wildHazard: IElementDefinition = {
  type: 'wild_hazard',
  text: 'wild_hazard',
  options: [{
    type: 'wild_hazard',
    text: 'wild_hazard_1',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_2',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_3',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_4',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_5',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_6',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_7',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_8',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_9',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_10',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_11',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_12',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_13',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_14',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_15',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_16',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_17',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_18',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_19',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_20',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_21',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_22',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_23',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_24',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_25',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_26',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_27',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_28',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_29',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_30',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_31',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_32',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_33',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_34',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_35',
  }, {
    type: 'wild_hazard',
    text: 'wild_hazard_36',
  }],
};

export {
  wildRegion,
  wildLandmark,
  wildStructure,
  wildTrait,
  wildDiscovery,
  wildActivity,
  wildHazard,
};
