import { IWorldDefinition } from '../typings';
import {
  animalAerial,
  animalAquatic,
  animalTerrestrial,
} from './animals';
import {
  cityActivity,
  cityBuildingRoom,
  cityDistrictTheme,
  cityEvent,
  cityLowerclassBuilding,
  cityTacticalBuildingFeature,
  cityTacticalStreetFeature,
  cityTheme,
  cityUpperclassBuilding,
} from './city';
import {
  dungeon,
  dungeonActivity,
  dungeonEntrance,
  dungeonForm,
  dungeonHazard,
  dungeonLayout,
  dungeonReward,
  dungeonRoom,
  dungeonRoomDetail,
  dungeonRuination,
  dungeonTrick,
} from './dungeon';
import {
  faction,
  factionGoal,
  factionTrait,
  factionType,
} from './faction';
import {
  miscellaneousItem,
  toolItem,
  treasure,
  treasureItem,
  treasureTrait,
  valuableMaterial,
  weaponItem,
  wornItem,
} from './item';
import {
  catastrophe,
  etherealEffect,
  etherealElement,
  etherealForm,
  insanity,
  magic,
  mutation,
  physicalEffect,
  physicalElement,
  physicalForm,
} from './magic';
import {
  monster,
  monsterAbility,
  monsterFeature,
  monsterPersonality,
  monsterTactic,
  monsterTrait,
  monsterWeakness,
} from './monster';
import {
  civilizedNpc,
  divinityDomain,
  femaleNames,
  lowerclassSurname,
  maleNames,
  mission,
  npc,
  npcAsset,
  npcCivilized,
  npcCivilizedFemale,
  npcCivilizedMale,
  npcGoal,
  npcLiability,
  npcLowerclassFemale,
  npcLowerclassMale,
  npcMethod,
  npcMisfortune,
  npcRelation,
  npcReputation,
  npcSecret,
  npcUnderworld,
  npcUnderworldFemale,
  npcUnderworldMale,
  npcUpperclassFemale,
  npcUpperclassMale,
  npcWilderness,
  npcWildernessFemale,
  npcWildernessMale,
  underworldNpc,
  upperclassSurname,
  wildernessNpc,
} from './npc';
import {
  appearance,
  background,
  clothes,
  mannerism,
  personality,
  pj,
  pjPhysical,
} from './pj';

export const worldDefinition: IWorldDefinition = {
  definitions: [
    miscellaneousItem,
    toolItem,
    treasure,
    treasureItem,
    treasureTrait,
    weaponItem,
    wornItem,
    valuableMaterial,
    npc,
    npcCivilized,
    npcUnderworld,
    npcWilderness,
    npcUnderworldFemale,
    npcUnderworldMale,
    npcWildernessFemale,
    npcWildernessMale,
    npcCivilizedFemale,
    npcCivilizedMale,
    npcUpperclassMale,
    npcUpperclassFemale,
    npcLowerclassMale,
    npcLowerclassFemale,
    npcAsset,
    npcLiability,
    npcMisfortune,
    npcSecret,
    npcMethod,
    npcReputation,
    npcRelation,
    mission,
    divinityDomain,
    femaleNames,
    maleNames,
    npcGoal,
    upperclassSurname,
    lowerclassSurname,
    civilizedNpc,
    wildernessNpc,
    underworldNpc,
    pj,
    appearance,
    background,
    clothes,
    mannerism,
    personality,
    pjPhysical,
    magic,
    etherealEffect,
    etherealElement,
    etherealForm,
    physicalEffect,
    physicalElement,
    physicalForm,
    mutation,
    insanity,
    catastrophe,
    animalAerial,
    animalAquatic,
    animalTerrestrial,
    monster,
    monsterAbility,
    monsterFeature,
    monsterTrait,
    monsterTactic,
    monsterPersonality,
    monsterWeakness,
    faction,
    factionType,
    factionTrait,
    factionGoal,
    cityTheme,
    cityEvent,
    cityDistrictTheme,
    cityUpperclassBuilding,
    cityLowerclassBuilding,
    cityActivity,
    cityBuildingRoom,
    cityTacticalStreetFeature,
    cityTacticalBuildingFeature,
    dungeon,
    dungeonEntrance,
    dungeonForm,
    dungeonLayout,
    dungeonRuination,
    dungeonReward,
    dungeonTrick,
    dungeonRoom,
    dungeonRoomDetail,
    dungeonHazard,
    dungeonActivity,
    ],
  alias: {
    item: [
      'miscellaneous_item',
      'worn_item',
      'weapon_item',
      'tool_item',
      'treasure_item',
    ],
    element: [
      'physical_element',
      'ethereal_element',
    ],
    effects: [
      'physical_effect',
      'ethereal_effect',
    ],
    forms: [
      'physical_forms',
      'ethereal_forms',
    ],
    animal: [
      'animal_aerial',
      'animal_terrestrial',
      'animal_aquatic',
    ],
    occupation: [
      'civilized_npc',
      'underworld_npc',
      'wilderness_npc',
    ],
  },
  existing: [],
};
