import { IWorldDefinition } from '../typings';
import {
  mrAnimalAerial,
  mrAnimalAquatic,
  mrAnimalTerrestrial,
} from './mr/animals';
import {
  mrCityActivity,
  mrCityBuilding,
  mrCityBuildingRoom,
  mrCityDistrictTheme,
  mrCityEvent,
  mrCityLowerclassBuilding,
  mrCityTacticalBuildingFeature,
  mrCityTacticalStreetFeature,
  mrCityTheme,
  mrCityUpperclassBuilding,
} from './mr/city';
import {
  mrDungeon,
  mrDungeonActivity,
  mrDungeonEntrance,
  mrDungeonForm,
  mrDungeonHazard,
  mrDungeonLayout,
  mrDungeonReward,
  mrDungeonRoom,
  mrDungeonRoomDetail,
  mrDungeonRuination,
  mrDungeonTrick,
} from './mr/dungeon';
import {
  mrFaction,
  mrFactionGoal,
  mrFactionTrait,
  mrFactionType,
} from './mr/faction';
import { mrInn, mrInnAdjective, mrInnName, mrInnQuirk } from './mr/inn';
import {
  mrBookTheme,
  mrMiscellaneousItem,
  mrToolItem,
  mrTreasure,
  mrTreasureItem,
  mrTreasureTrait,
  mrValuableMaterial,
  mrWeaponItem,
  mrWornItem,
} from './mr/item';
import {
  mrCatastrophe,
  mrEtherealEffect,
  mrEtherealElement,
  mrEtherealForm,
  mrInsanity,
  mrMagic,
  mrMagicIngredient,
  mrMutation,
  mrPhysicalEffect,
  mrPhysicalElement,
  mrPhysicalForm,
  mrPotion,
} from './mr/magic';
import {
  mrMonster,
  mrMonsterAbility,
  mrMonsterFeature,
  mrMonsterPersonality,
  mrMonsterTactic,
  mrMonsterTrait,
  mrMonsterWeakness,
} from './mr/monster';
import {
  mrCivilizedNpc,
  mrDivinityDomain,
  mrFemaleNames,
  mrLowerclassSurname,
  mrMaleNames,
  mrMission,
  mrNpc,
  mrNpcAsset,
  mrNpcCivilized,
  mrNpcCivilizedFemale,
  mrNpcCivilizedMale,
  mrNpcGoal,
  mrNpcLiability,
  mrNpcLowerclassFemale,
  mrNpcLowerclassMale,
  mrNpcMethod,
  mrNpcMisfortune,
  mrNpcRelation,
  mrNpcReputation,
  mrNpcSecret,
  mrNpcUnderworld,
  mrNpcUnderworldFemale,
  mrNpcUnderworldMale,
  mrNpcUpperclassFemale,
  mrNpcUpperclassMale,
  mrNpcWilderness,
  mrNpcWildernessFemale,
  mrNpcWildernessMale,
  mrUnderworldNpc,
  mrUpperclassSurname,
  mrWildernessNpc,
} from './mr/npc';
import {
  mrAppearance,
  mrBackground,
  mrClothes,
  mrMannerism,
  mrPersonality,
  mrPj,
  mrPjPhysical,
} from './mr/pj';
import {
  mrEdiblePlant,
  mrPlant,
  mrPoisonousPlant,
} from './mr/plant';
import {
  mrTrap,
  mrTrapEffect,
  mrTrapTrigger,
} from './mr/trap';
import {
  mrWildActivity,
  mrWildDiscovery,
  mrWildHazard,
  mrWildLandmark,
  mrWildRegion,
  mrWildStructure,
  mrWildTrait,
} from './mr/wild';
import { mythicEvent, mythicEventFocus, mythicEventMeaning } from './mythic/random_event';

export const worldDefinition: IWorldDefinition = {
  definitions: [
    mrMiscellaneousItem,
    mrToolItem,
    mrTreasure,
    mrTreasureItem,
    mrTreasureTrait,
    mrWeaponItem,
    mrWornItem,
    mrValuableMaterial,
    mrCivilizedNpc,
    mrDivinityDomain,
    mrFemaleNames,
    mrLowerclassSurname,
    mrMaleNames,
    mrMission,
    mrNpc,
    mrNpcAsset,
    mrNpcCivilized,
    mrNpcCivilizedFemale,
    mrNpcCivilizedMale,
    mrNpcGoal,
    mrNpcLiability,
    mrNpcLowerclassFemale,
    mrNpcLowerclassMale,
    mrNpcMethod,
    mrNpcMisfortune,
    mrNpcRelation,
    mrNpcReputation,
    mrNpcSecret,
    mrNpcUnderworld,
    mrNpcUnderworldFemale,
    mrNpcUnderworldMale,
    mrNpcUpperclassFemale,
    mrNpcUpperclassMale,
    mrNpcWilderness,
    mrNpcWildernessFemale,
    mrNpcWildernessMale,
    mrUnderworldNpc,
    mrUpperclassSurname,
    mrWildernessNpc,
    mrAppearance,
    mrBackground,
    mrClothes,
    mrMannerism,
    mrPersonality,
    mrPj,
    mrPjPhysical,
    mrCatastrophe,
    mrEtherealEffect,
    mrEtherealElement,
    mrEtherealForm,
    mrInsanity,
    mrMagic,
    mrMagicIngredient,
    mrMutation,
    mrPhysicalEffect,
    mrPhysicalElement,
    mrPhysicalForm,
    mrPotion,
    mrAnimalAerial,
    mrAnimalAquatic,
    mrAnimalTerrestrial,
    mrMonster,
    mrMonsterAbility,
    mrMonsterFeature,
    mrMonsterPersonality,
    mrMonsterTactic,
    mrMonsterTrait,
    mrMonsterWeakness,
    mrFaction,
    mrFactionType,
    mrFactionTrait,
    mrFactionGoal,
    mrCityTheme,
    mrCityEvent,
    mrCityDistrictTheme,
    mrCityBuilding,
    mrCityUpperclassBuilding,
    mrCityLowerclassBuilding,
    mrCityActivity,
    mrCityBuildingRoom,
    mrCityTacticalStreetFeature,
    mrCityTacticalBuildingFeature,
    mrDungeon,
    mrDungeonEntrance,
    mrDungeonForm,
    mrDungeonLayout,
    mrDungeonRuination,
    mrDungeonReward,
    mrDungeonTrick,
    mrDungeonRoom,
    mrDungeonRoomDetail,
    mrDungeonHazard,
    mrDungeonActivity,
    mrTrap,
    mrTrapEffect,
    mrTrapTrigger,
    mrWildActivity,
    mrWildDiscovery,
    mrWildHazard,
    mrWildLandmark,
    mrWildRegion,
    mrWildStructure,
    mrWildTrait,
    mrEdiblePlant,
    mrPlant,
    mrPoisonousPlant,
    mrInn,
    mrInnAdjective,
    mrInnName,
    mrInnQuirk,
    mrBookTheme,
    mythicEvent,
    mythicEventFocus,
    mythicEventMeaning,
    ],
  alias: {
    mr_item: [
      'mr_miscellaneous_item',
      'mr_worn_item',
      'mr_weapon_item',
      'mr_tool_item',
      'mr_treasure_item',
    ],
    mr_element: [
      'mr_physical_element',
      'mr_ethereal_element',
    ],
    mr_effects: [
      'mr_physical_effect',
      'mr_ethereal_effect',
    ],
    mr_forms: [
      'mr_physical_forms',
      'mr_ethereal_forms',
    ],
    mr_animal: [
      'mr_animal_aerial',
      'mr_animal_terrestrial',
      'mr_animal_aquatic',
    ],
    mr_occupation: [
      'mr_civilized_npc',
      'mr_underworld_npc',
      'mr_wilderness_npc',
    ],
  },
  existing: [],
};
