import { IWorldDefinition } from '../typings';
import {
  animalAerial,
  animalAquatic,
  animalTerrestrial,
} from './animals';
import {
  faction,
} from './city';
import {
  miscellaneousItemsDef,
  toolItemsDef,
  treasureItemsDef,
  weaponItemsDef,
  wornItemsDef,
} from './items';
import {
  etherealEffect,
  etherealElement,
  etherealForm,
  magic,
  physicalEffect,
  physicalElement,
  physicalForm,
} from './magic';
import {
  monster,
  monsterAbility,
  monsterFeature,
  monsterPersonality,
  monsterTactic,
  monsterTrait,
} from './monster';
import {
  civilizedNpc,
  divinityDomain,
  femaleNames,
  lowerclassSurname,
  maleNames,
  mission,
  npc,
  npcAsset,
  npcGoal,
  npcLiability,
  npcLowerclassFemale,
  npcLowerclassMale,
  npcMethod,
  npcMisfortune,
  npcRelation,
  npcReputation,
  npcSecret,
  npcUpperclassFemale,
  npcUpperclassMale,
  underworldNpc,
  upperclassSurname,
  wildernessNpc,
} from './npc';
import {
  appearance,
  background,
  clothes,
  mannerism,
  personality,
  pj,
  pjPhysical,
} from './pj';

export const worldDefinition: IWorldDefinition = {
  definitions: [
    miscellaneousItemsDef,
    wornItemsDef,
    weaponItemsDef,
    toolItemsDef,
    treasureItemsDef,
    npc,
    npcUpperclassMale,
    npcUpperclassFemale,
    npcLowerclassMale,
    npcLowerclassFemale,
    npcAsset,
    npcLiability,
    npcMisfortune,
    npcSecret,
    npcMethod,
    npcReputation,
    npcRelation,
    mission,
    divinityDomain,
    femaleNames,
    maleNames,
    npcGoal,
    upperclassSurname,
    lowerclassSurname,
    civilizedNpc,
    wildernessNpc,
    underworldNpc,
    pj,
    appearance,
    background,
    clothes,
    mannerism,
    personality,
    pjPhysical,
    magic,
    etherealEffect,
    etherealElement,
    etherealForm,
    physicalEffect,
    physicalElement,
    physicalForm,
    animalAerial,
    animalAquatic,
    animalTerrestrial,
    monster,
    monsterAbility,
    monsterFeature,
    monsterTrait,
    monsterTactic,
    monsterPersonality,
    faction,
  ],
  alias: {
    item: [
      'miscellaneous_items',
      'worn_items',
      'weapon_items',
      'tool_items',
      'treasure_items',
    ],
    element: [
      'physical_element',
      'ethereal_element',
    ],
    effects: [
      'physical_effects',
      'ethereal_effects',
    ],
    forms: [
      'physical_forms',
      'ethereal_forms',
    ],
    animal: [
      'animal_aerial',
      'animal_terrestrial',
      'animal_aquatic',
    ],
    occupation: [
      'civilized_npc',
      'underworld_npc',
      'wilderness_npc',
    ],
  },
  existing: [],
};
