import { IElementDefinition } from '../typings';

const miscellaneousItemsDef: IElementDefinition = {
  type: 'miscellaneous_items',
  options: [{
    type: 'miscellaneous_items_1',
  }, {
    type: 'miscellaneous_items_2',
  }, {
    type: 'miscellaneous_items_3',
  }, {
    type: 'miscellaneous_items_4',
  }, {
    type: 'miscellaneous_items_5',
  }, {
    type: 'miscellaneous_items_6',
  }, {
    type: 'miscellaneous_items_7',
  }, {
    type: 'miscellaneous_items_8',
  }, {
    type: 'miscellaneous_items_9',
  }, {
    type: 'miscellaneous_items_10',
  }, {
    type: 'miscellaneous_items_11',
  }, {
    type: 'miscellaneous_items_12',
  }, {
    type: 'miscellaneous_items_13',
  }, {
    type: 'miscellaneous_items_14',
  }, {
    type: 'miscellaneous_items_15',
  }, {
    type: 'miscellaneous_items_16',
  }, {
    type: 'miscellaneous_items_17',
  }, {
    type: 'miscellaneous_items_18',
  }, {
    type: 'miscellaneous_items_19',
  }, {
    type: 'miscellaneous_items_20',
  }, {
    type: 'miscellaneous_items_21',
  }, {
    type: 'miscellaneous_items_22',
  }, {
    type: 'miscellaneous_items_23',
  }, {
    type: 'miscellaneous_items_24',
  }, {
    type: 'miscellaneous_items_24',
  }, {
    type: 'miscellaneous_items_26',
  }, {
    type: 'miscellaneous_items_27',
  }, {
    type: 'miscellaneous_items_28',
  }, {
    type: 'miscellaneous_items_29',
  }, {
    type: 'miscellaneous_items_30',
  }, {
    type: 'miscellaneous_items_31',
  }, {
    type: 'miscellaneous_items_32',
  }, {
    type: 'miscellaneous_items_33',
  }, {
    type: 'miscellaneous_items_34',
  }, {
    type: 'miscellaneous_items_35',
  }]
}

const wornItemsDef: IElementDefinition = {
  type: 'worn_items',
  options: [{
    type: 'worn_items_1',
  }, {
    type: 'worn_items_2',
  }, {
    type: 'worn_items_3',
  }, {
    type: 'worn_items_4',
  }, {
    type: 'worn_items_5',
  }, {
    type: 'worn_items_6',
  }, {
    type: 'worn_items_7',
  }, {
    type: 'worn_items_8',
  }, {
    type: 'worn_items_9',
  }, {
    type: 'worn_items_10',
  }, {
    type: 'worn_items_11',
  }, {
    type: 'worn_items_12',
  }, {
    type: 'worn_items_13',
  }, {
    type: 'worn_items_14',
  }, {
    type: 'worn_items_15',
  }, {
    type: 'worn_items_16',
  }, {
    type: 'worn_items_17',
  }, {
    type: 'worn_items_18',
  }, {
    type: 'worn_items_19',
  }, {
    type: 'worn_items_20',
  }, {
    type: 'worn_items_21',
  }, {
    type: 'worn_items_22',
  }, {
    type: 'worn_items_23',
  }, {
    type: 'worn_items_24',
  }, {
    type: 'worn_items_24',
  }, {
    type: 'worn_items_26',
  }, {
    type: 'worn_items_27',
  }, {
    type: 'worn_items_28',
  }, {
    type: 'worn_items_29',
  }, {
    type: 'worn_items_30',
  }, {
    type: 'worn_items_31',
  }, {
    type: 'worn_items_32',
  }, {
    type: 'worn_items_33',
  }, {
    type: 'worn_items_34',
  }, {
    type: 'worn_items_35',    
  }]
}

const weaponItemsDef: IElementDefinition = {
  type: 'weapon_items',
  options: [{
    type: 'weapon_items_1',
  }, {
    type: 'weapon_items_2',
  }, {
    type: 'weapon_items_3',
  }, {
    type: 'weapon_items_4',
  }, {
    type: 'weapon_items_5',
  }, {
    type: 'weapon_items_6',
  }, {
    type: 'weapon_items_7',
  }, {
    type: 'weapon_items_8',
  }, {
    type: 'weapon_items_9',
  }, {
    type: 'weapon_items_10',
  }, {
    type: 'weapon_items_11',
  }, {
    type: 'weapon_items_12',
  }, {
    type: 'weapon_items_13',
  }, {
    type: 'weapon_items_14',
  }, {
    type: 'weapon_items_15',
  }, {
    type: 'weapon_items_16',
  }, {
    type: 'weapon_items_17',
  }, {
    type: 'weapon_items_18',
  }, {
    type: 'weapon_items_19',
  }, {
    type: 'weapon_items_20',
  }, {
    type: 'weapon_items_21',
  }, {
    type: 'weapon_items_22',
  }, {
    type: 'weapon_items_23',
  }, {
    type: 'weapon_items_24',
  }, {
    type: 'weapon_items_24',
  }, {
    type: 'weapon_items_26',
  }, {
    type: 'weapon_items_27',
  }, {
    type: 'weapon_items_28',
  }, {
    type: 'weapon_items_29',
  }, {
    type: 'weapon_items_30',
  }, {
    type: 'weapon_items_31',
  }, {
    type: 'weapon_items_32',
  }, {
    type: 'weapon_items_33',
  }, {
    type: 'weapon_items_34',
  }, {
    type: 'weapon_items_35',    
  }]
}

const toolItemsDef: IElementDefinition = {
  type: 'tool_items',
  options: [{
    type: 'tool_items_1',
  }, {
    type: 'tool_items_2',
  }, {
    type: 'tool_items_3',
  }, {
    type: 'tool_items_4',
  }, {
    type: 'tool_items_5',
  }, {
    type: 'tool_items_6',
  }, {
    type: 'tool_items_7',
  }, {
    type: 'tool_items_8',
  }, {
    type: 'tool_items_9',
  }, {
    type: 'tool_items_10',
  }, {
    type: 'tool_items_11',
  }, {
    type: 'tool_items_12',
  }, {
    type: 'tool_items_13',
  }, {
    type: 'tool_items_14',
  }, {
    type: 'tool_items_15',
  }, {
    type: 'tool_items_16',
  }, {
    type: 'tool_items_17',
  }, {
    type: 'tool_items_18',
  }, {
    type: 'tool_items_19',
  }, {
    type: 'tool_items_20',
  }, {
    type: 'tool_items_21',
  }, {
    type: 'tool_items_22',
  }, {
    type: 'tool_items_23',
  }, {
    type: 'tool_items_24',
  }, {
    type: 'tool_items_24',
  }, {
    type: 'tool_items_26',
  }, {
    type: 'tool_items_27',
  }, {
    type: 'tool_items_28',
  }, {
    type: 'tool_items_29',
  }, {
    type: 'tool_items_30',
  }, {
    type: 'tool_items_31',
  }, {
    type: 'tool_items_32',
  }, {
    type: 'tool_items_33',
  }, {
    type: 'tool_items_34',
  }, {
    type: 'tool_items_35',
  }]
}

const treasureItemsDef: IElementDefinition = {
  type: 'treasure_items',
  options: [{
    type: 'treasure_items_1',
  }, {
    type: 'treasure_items_2',
  }, {
    type: 'treasure_items_3',
  }, {
    type: 'treasure_items_4',
  }, {
    type: 'treasure_items_5',
  }, {
    type: 'treasure_items_6',
  }, {
    type: 'treasure_items_7',
  }, {
    type: 'treasure_items_8',
  }, {
    type: 'treasure_items_9',
  }, {
    type: 'treasure_items_10',
  }, {
    type: 'treasure_items_11',
  }, {
    type: 'treasure_items_12',
  }, {
    type: 'treasure_items_13',
  }, {
    type: 'treasure_items_14',
  }, {
    type: 'treasure_items_15',
  }, {
    type: 'treasure_items_16',
  }, {
    type: 'treasure_items_17',
  }, {
    type: 'treasure_items_18',
  }, {
    type: 'treasure_items_19',
  }, {
    type: 'treasure_items_20',
  }, {
    type: 'treasure_items_21',
  }, {
    type: 'treasure_items_22',
  }, {
    type: 'treasure_items_23',
  }, {
    type: 'treasure_items_24',
  }, {
    type: 'treasure_items_24',
  }, {
    type: 'treasure_items_26',
  }, {
    type: 'treasure_items_27',
  }, {
    type: 'treasure_items_28',
  }, {
    type: 'treasure_items_29',
  }, {
    type: 'treasure_items_30',
  }, {
    type: 'treasure_items_31',
  }, {
    type: 'treasure_items_32',
  }, {
    type: 'treasure_items_33',
  }, {
    type: 'treasure_items_34',
  }, {
    type: 'treasure_items_35',   
  }]
};

export {
  miscellaneousItemsDef,
  wornItemsDef,
  weaponItemsDef,
  toolItemsDef,
  treasureItemsDef
};
