import { ERandomOption, IElementDefinition } from '../typings';

const pj: IElementDefinition = {
  type: 'pj',
  text: 'pj',
  related: {
    appearance: {
      search: [{
        type: 'pj_appearance',
        random: ERandomOption.random,
      }],
    },
    physical: {
      search: [{
        type: 'pj_physical',
        random: ERandomOption.random,
      }],
    },
    clothes: {
      search: [{
        type: 'pj_clothes',
        random: ERandomOption.random,
      }],
    },
    background: {
      search: [{
        type: 'pj_background',
        random: ERandomOption.random,
      }],
    },
    mannerism: {
      search: [{
        type: 'pj_mannerism',
        random: ERandomOption.random,
      }],
    },
    personality: {
      search: [{
        type: 'pj_personality',
        random: ERandomOption.random,
      }],
    },
  },
};

const pjAppearance: IElementDefinition = {
  type: 'pj_appearance',
  text: 'pj_appearance',
  options: [{
    type: 'pj_appearance',
    text: 'pj_appearance_1',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_2',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_3',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_4',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_5',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_6',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_7',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_8',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_9',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_10',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_11',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_12',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_13',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_14',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_15',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_16',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_17',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_18',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_19',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_20',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_21',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_22',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_23',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_24',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_25',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_26',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_27',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_28',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_29',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_30',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_31',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_32',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_33',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_34',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_35',
  }, {
    type: 'pj_appearance',
    text: 'pj_appearance_36',
  }],
};

const pjPhysical: IElementDefinition = {
  type: 'pj_physical',
  text: 'pj_physical',
  options: [{
    type: 'pj_physical',
    text: 'pj_physical_1',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_2',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_3',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_4',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_5',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_6',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_7',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_8',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_9',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_10',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_11',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_12',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_13',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_14',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_15',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_16',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_17',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_18',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_19',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_20',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_21',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_22',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_23',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_24',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_25',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_26',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_27',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_28',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_29',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_30',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_31',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_32',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_33',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_34',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_35',
  }, {
    type: 'pj_physical',
    text: 'pj_physical_36',
  }],
};

const pjBackground: IElementDefinition = {
  type: 'pj_background',
  text: 'pj_background',
  options: [{
    type: 'pj_background',
    text: 'pj_background_1',
  }, {
    type: 'pj_background',
    text: 'pj_background_2',
  }, {
    type: 'pj_background',
    text: 'pj_background_3',
  }, {
    type: 'pj_background',
    text: 'pj_background_4',
  }, {
    type: 'pj_background',
    text: 'pj_background_5',
  }, {
    type: 'pj_background',
    text: 'pj_background_6',
  }, {
    type: 'pj_background',
    text: 'pj_background_7',
  }, {
    type: 'pj_background',
    text: 'pj_background_8',
  }, {
    type: 'pj_background',
    text: 'pj_background_9',
  }, {
    type: 'pj_background',
    text: 'pj_background_10',
  }, {
    type: 'pj_background',
    text: 'pj_background_11',
  }, {
    type: 'pj_background',
    text: 'pj_background_12',
  }, {
    type: 'pj_background',
    text: 'pj_background_13',
  }, {
    type: 'pj_background',
    text: 'pj_background_14',
  }, {
    type: 'pj_background',
    text: 'pj_background_15',
  }, {
    type: 'pj_background',
    text: 'pj_background_16',
  }, {
    type: 'pj_background',
    text: 'pj_background_17',
  }, {
    type: 'pj_background',
    text: 'pj_background_18',
  }, {
    type: 'pj_background',
    text: 'pj_background_19',
  }, {
    type: 'pj_background',
    text: 'pj_background_20',
  }, {
    type: 'pj_background',
    text: 'pj_background_21',
  }, {
    type: 'pj_background',
    text: 'pj_background_22',
  }, {
    type: 'pj_background',
    text: 'pj_background_23',
  }, {
    type: 'pj_background',
    text: 'pj_background_24',
  }, {
    type: 'pj_background',
    text: 'pj_background_25',
  }, {
    type: 'pj_background',
    text: 'pj_background_26',
  }, {
    type: 'pj_background',
    text: 'pj_background_27',
  }, {
    type: 'pj_background',
    text: 'pj_background_28',
  }, {
    type: 'pj_background',
    text: 'pj_background_29',
  }, {
    type: 'pj_background',
    text: 'pj_background_30',
  }, {
    type: 'pj_background',
    text: 'pj_background_31',
  }, {
    type: 'pj_background',
    text: 'pj_background_32',
  }, {
    type: 'pj_background',
    text: 'pj_background_33',
  }, {
    type: 'pj_background',
    text: 'pj_background_34',
  }, {
    type: 'pj_background',
    text: 'pj_background_35',
  }, {
    type: 'pj_background',
    text: 'pj_background_36',
  }],
};

const pjPersonality: IElementDefinition = {
  type: 'pj_personality',
  text: 'pj_personality',
  options: [{
    type: 'pj_personality',
    text: 'pj_personality_1',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_2',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_3',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_4',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_5',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_6',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_7',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_8',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_9',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_10',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_11',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_12',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_13',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_14',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_15',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_16',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_17',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_18',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_19',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_20',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_21',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_22',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_23',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_24',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_25',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_26',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_27',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_28',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_29',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_30',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_31',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_32',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_33',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_34',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_35',
  }, {
    type: 'pj_personality',
    text: 'pj_personality_36',
  }],
};

const pjClothes: IElementDefinition = {
  type: 'pj_clothes',
  text: 'pj_clothes',
  options: [{
    type: 'pj_clothes',
    text: 'pj_clothes_1',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_2',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_3',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_4',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_5',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_6',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_7',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_8',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_9',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_10',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_11',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_12',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_13',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_14',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_15',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_16',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_17',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_18',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_19',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_20',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_21',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_22',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_23',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_24',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_25',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_26',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_27',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_28',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_29',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_30',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_31',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_32',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_33',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_34',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_35',
  }, {
    type: 'pj_clothes',
    text: 'pj_clothes_36',
  }],
};

const pjMannerism: IElementDefinition = {
  type: 'pj_mannerism',
  text: 'pj_mannerism',
  options: [{
    type: 'pj_mannerism',
    text: 'pj_mannerism_1',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_2',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_3',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_4',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_5',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_6',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_7',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_8',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_9',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_10',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_11',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_12',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_13',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_14',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_15',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_16',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_17',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_18',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_19',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_20',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_21',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_22',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_23',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_24',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_25',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_26',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_27',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_28',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_29',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_30',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_31',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_32',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_33',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_34',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_35',
  }, {
    type: 'pj_mannerism',
    text: 'pj_mannerism_36',
  }],
};

export {
  pj,
  pjAppearance,
  pjPersonality,
  pjPhysical,
  pjBackground,
  pjMannerism,
  pjClothes,
};
